#端口号
server:
  port: 8081
  servlet:
    session:
      timeout: 1D

spring:
  profiles:
    active: dev
  config:
    use-legacy-processing: true
    
#登录用户名密码
admin:
  username: admin
  password: admin



crawl:
  update:
    #爬虫自动更新的线程数
    #建议小说数量不多或者正在运行新书入库爬虫的情况下设置为1即可
    #随着小说数量的增多可以逐渐增加，但建议不要超出CPU的线程数
    thread: 1
  # 采集间隔时间，单位：毫秒
  interval:
    min: 300
    max: 500





